version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    networks: 
      - broker-nsq
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd
  nsqd:
    image: nsqio/nsq
    hostname: nsqd
    depends_on:
      - nsqlookupd
    networks: 
      - broker-nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
  nsqadmin:
    image: nsqio/nsq
    hostname: nsqadmin
    depends_on:
      - nsqlookupd
    networks: 
      - broker-nsq
    ports:
      - "4171:4171"
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161

networks: 
  broker-nsq:
    driver: bridge 